### ISSUE TITLE
Sidebar Links Not Working

### ISSUE THREAD

**Issue by GonzoKK** [James231/Documentation-Templater#1]
Hi - this project looks very promising.  

Can you check index,html in Output folder. It seems a number of closing tags are missing eg html, body etc 

![image](https://user-images.githubusercontent.com/38913162/89938311-9b3bcc00-dc16-11ea-9ceb-a11cfec81f9b.png)

**Comment by GonzoKK** [comment]
oops my bad, works fine when running http-server

**Comment by richardsantink** [comment]
I sent you a message directly, but perhaps here is a more appropriate location. :) I would agree with GonzoKK that it appears the links from the sidebar nav do no work, without HTTP services running. However, this could really reach its full potential if it can be run locally, and  if you could include a setting for the http root when it's implemented on an http server.  For now, I've been using regex replacement to sub in href=/ with href=./ so that I can have it in directories other than the root.  Can this functionality (perhaps by way of config file) be added?

Contact me if it's a funding matter, as this could be an extremely useful, lightweight tool.

Regards,
Rich Santink
